name: Specs

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.2.0
          - 3.3.0
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Update apt
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo apt-get update -qq

    - name: Install libvips
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo apt-get install --fix-missing libvips

    - name: RSpec
      run: bin/rspec